version: 2
updates:
- package-ecosystem: github-actions
  cooldown:
    default-days: 7
  directory: /
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
      - "*"
- package-ecosystem: uv
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  groups:
    dev-packages:
      dependency-type: development
      patterns:
      - '*'
    prod-packages:
      dependency-type: production
      patterns:
      - '*'
- package-ecosystem: pre-commit
  cooldown:
    default-days: 7
  directory: /
  schedule:
    interval: weekly
