exclude: source/_static/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: check-toml
    exclude: uv.lock
  - id: check-added-large-files
    exclude: uv.lock
  - id: check-merge-conflict
  - id: debug-statements
  - id: mixed-line-ending
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: e8f7d69b957a30acb2c875078d5fd012de24b64c # v0.16.7
  hooks:
  - id: ruff
    args: [--fix, --show-fixes]
  - id: ruff-format
- repo: https://github.com/executablebooks/mdformat
  rev: 82912cdaea4fb830f751504486a7879c70526547 # 1.0.0
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-ruff
    - mdformat-myst
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f # v2.16.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --preserve-quotes]
  - id: pretty-format-toml
    args: [--autofix]
    exclude: uv.lock
- repo: https://github.com/gitleaks/gitleaks
  rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # v8.30.1
  hooks:
  - id: gitleaks
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: cef8b8350da46d8114c7e6b7272aebdccdf193ce # v1.30.0
  hooks:
  - id: zizmor
    args: [--no-progress, --fix]
    exclude: .github/workflows/main.yaml
- repo: https://github.com/PyCQA/doc8
  rev: 2a7a5eef1de341fab48019faf3de8a64ac2ad900 # v2.0.0
  hooks:
  - id: doc8
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 7720020191168f707a43279c65b6bf9cdf7ed04e # 0.12.10
  hooks:
  - id: uv-lock
