# Copyright 2026 European Union
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Improve the Markdown pages generated by sphinx-llm and link to them.

Relies on nbsphinx and sphinx-design internals: renamed nodes break the import and
unknown ones emit warnings, which fail the CI build.
"""

import posixpath

from docutils import nodes
from edh_icons import EdhOcticon
from nbconvert.filters import strip_ansi
from nbsphinx import AdmonitionNode, CodeAreaNode, FancyOutputNode, GalleryNode
from sphinx import addnodes
from sphinx.transforms.post_transforms import SphinxPostTransform
from sphinx_design.shared import PassthroughTextElement
from sphinx_iconify.roles import iconify_icon
from sphinxcontrib.youtube.youtube import youtube


def _has_class(node, name):
    return isinstance(node, nodes.Element) and name in node.get("classes", [])


def _inside(node, class_name):
    while node is not None:
        if _has_class(node, class_name):
            return True
        node = node.parent
    return False


def _remove(node):
    if node.parent is not None:
        node.parent.remove(node)


class NotebookCells(SphinxPostTransform):
    """Turn nbsphinx cells into fenced code blocks with plain-text outputs.

    Runs before OnlyNodeTransform (priority 50), which resolves ``only`` nodes.
    """

    default_priority = 40
    formats = ("markdown",)

    def run(self, **kwargs):
        for only in list(self.document.findall(addnodes.only)):
            # nbsphinx wraps the "[1]:" prompt of every cell in ``only:: html``.
            if any(_has_class(child, "prompt") for child in only.children):
                _remove(only)
            # Rich outputs come as an ``only:: html`` / ``only:: latex`` pair:
            # the LaTeX variant falls back to text/plain instead of HTML.
            elif any(_has_class(n, "nboutput") for n in only.findall(nodes.container)):
                if only["expr"] == "html":
                    _remove(only)
                elif only["expr"] == "latex":
                    only.replace_self(only.children)

        for node in list(
            self.document.findall(
                lambda n: isinstance(n, (CodeAreaNode, FancyOutputNode))
            )
        ):
            node.replace_self(node.children)

        # Plain-text outputs are emitted three times: raw html, latex and text.
        for raw in list(self.document.findall(nodes.raw)):
            formats = raw.get("format", "").split()
            if "text" in formats and _inside(raw, "nboutput"):
                text = strip_ansi(raw.astext())
                raw.replace_self(nodes.literal_block(text, text, language="text"))
            elif "html" in formats or "latex" in formats:
                _remove(raw)

        for block in self.document.findall(nodes.literal_block):
            if block.get("language") == "ipython3":
                block["language"] = "python"

        # Output images point to the nbsphinx doctree folder: use the copies
        # published by the HTML build, with absolute URLs so that they survive
        # the concatenation into llms-full.txt.
        base_url = self.config.html_baseurl.rstrip("/")
        if base_url:
            for image in self.document.findall(nodes.image):
                if _inside(image, "nboutput"):
                    name = posixpath.basename(image["uri"])
                    image["uri"] = f"{base_url}/_images/{name}"


class MarkdownCleanup(SphinxPostTransform):
    """Keep content that sphinx-markdown-builder would silently drop."""

    default_priority = 40
    formats = ("markdown",)

    def run(self, **kwargs):
        for node in list(
            self.document.findall(lambda n: isinstance(n, (EdhOcticon, iconify_icon)))
        ):
            _remove(node)

        for container in list(self.document.findall(nodes.container)):
            if _has_class(container, "edh-notebook-actions"):
                _remove(container)

        # Card titles and card links.
        for node in list(self.document.findall(PassthroughTextElement)):
            if any(
                _has_class(ref, "sd-stretched-link")
                for ref in node.findall(nodes.reference)
            ):
                node.replace_self(nodes.paragraph("", "", *node.children))
            else:
                title = nodes.strong("", "", *node.children)
                node.replace_self(nodes.paragraph("", "", title))

        # Generic and nbsphinx admonitions (e.g. alert boxes) have no Markdown handler.
        for admonition in list(
            self.document.findall(
                lambda n: isinstance(n, (nodes.admonition, AdmonitionNode))
            )
        ):
            title = admonition.next_node(nodes.title)
            body = [child for child in admonition.children if child is not title]
            heading = []
            if title is not None:
                heading = [
                    nodes.paragraph("", "", nodes.strong("", "", *title.children))
                ]
            admonition.parent.replace(admonition, heading + body)

        for video in list(self.document.findall(youtube)):
            url = f"https://www.youtube.com/watch?v={video['id']}"
            link = nodes.reference(url, url, refuri=url)
            video.replace_self(nodes.paragraph("", "", nodes.Text("Video: "), link))

        # nbsphinx_prolog puts a note before the notebook title, and sphinx-llm
        # takes the first heading ("#### NOTE") as the page title in llms.txt.
        # Move it after the introduction, before the first subsection.
        section = next(
            (c for c in self.document.children if isinstance(c, nodes.section)), None
        )
        if section is not None:
            for child in self.document.children[: self.document.index(section)]:
                if isinstance(child, nodes.note):
                    self.document.remove(child)
                    subsections = [c for c in section if isinstance(c, nodes.section)]
                    index = (
                        section.index(subsections[0]) if subsections else len(section)
                    )
                    section.insert(index, child)
                elif isinstance(child, nodes.transition):
                    self.document.remove(child)


def gallery_to_list(app, doctree, docname):
    """Replace nbsphinx galleries with a list of links (entries exist only now)."""
    if app.builder.format != "markdown":
        return
    for gallery in list(doctree.findall(GalleryNode)):
        items = nodes.bullet_list()
        for title, uri, _thumbnail, tooltip in gallery["entries"]:
            link = nodes.reference(title, title, refuri=uri, internal=True)
            paragraph = nodes.paragraph("", "", link)
            if tooltip:
                paragraph += nodes.Text(f": {tooltip}")
            items += nodes.list_item("", paragraph)
        gallery.replace_self(items)


def ai_links_to_markdown(app, pagename, templatename, context, doctree):
    """Point the "Copy page" and "Open in ..." links to the generated Markdown."""
    base_url = app.config.html_baseurl.rstrip("/")
    if base_url and getattr(app.config, "llms_txt_enabled", False):
        context["view_source_link"] = lambda filename: (
            f"{base_url}/{posixpath.splitext(filename)[0]}.md"
        )


def setup(app):
    app.add_post_transform(NotebookCells)
    app.add_post_transform(MarkdownCleanup)
    # After the nbsphinx doctree-resolved handler, which fills the entries.
    app.connect("doctree-resolved", gallery_to_list, priority=600)
    app.connect("html-page-context", ai_links_to_markdown)

    return {
        "version": "0.1",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
