name: On-push

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
    - name: Run code quality tools
      run: make qa

  docs-check:
    name: Check docs build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
    - name: Check build
      run: |
        make html SPHINXOPTS="-W --keep-going"
